version: '3'

services:
  app:
    container_name: "s3_course_api"
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 8000:8000
    networks:
      - backend-network
  mongo:
    container_name: "s3_course_db"
    image: mongo:latest
    volumes:
      - ~/mongo:/data/db
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=app_user
      - MONGO_INITDB_ROOT_PASSWORD=app_password
      - MONGO_INITDB_DATABASE=admin
    networks:
      - backend-network

networks:
  backend-network:
    driver: bridge
